name: elmokhtaser
description: Educational application.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  lottie: ^1.2.1
  flutter_bloc: ^8.0.1
  easy_localization: ^3.0.0
  google_fonts: ^2.3.1
  sizer: ^2.0.15
  flutter_launcher_icons: ^0.9.2
  flutter_staggered_animations: ^1.0.0
  flutter_rating_bar: ^4.0.0
  dio: ^4.0.6
  intl: ^0.17.0
  dotted_border: ^2.0.0
  alert: ^2.0.1
  shared_preferences: ^2.0.15
  slide_countdown: ^0.2.4
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.2
  pdf: ^3.8.1
  path_provider: ^2.0.11
  screenshot: ^1.2.3
  firebase_core: ^2.4.1
  printing: ^5.9.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^9.5.3
  flutter_downloader: ^1.7.4
  permission_handler: ^10.0.0
  connectivity_plus: ^2.3.5
  cached_network_image: ^3.2.0
  drag_and_drop_lists: ^0.3.2+2
  vimeo_video_player:
   git:
     url: https://github.com/Hadeer-Sherif/vimeo_video_player.git
     ref: master
   
  flutter_html: ^2.2.1
  flutter_widget_from_html_core: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/translations/



  
  fonts:
    - family: Iconly-Broken
      fonts:
        - asset: assets/fonts/icons.ttf
